// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright  Google LLC

// snippet.show
import GoogleCloudWkt
import GoogleCloudLocation
import Foundation

func sample(client: some Locations) async throws {
  let response = try await client.listLocations(
    request: ListLocationsRequest( /* set fields */)
  )
  print("Success: \(response)")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      let client = try GoogleCloudLocation.Clients.LocationsClient()
      try await sample(client: client)
    } catch {
      print("Error: \(error)")
    }
  }
}
