// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudWkt

/// The response message for [Locations.ListLocations][google.cloud.location.Locations.ListLocations].
public struct ListLocationsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable {
  /// A list of locations that matches the specified filter in the request.
  public var locations: [Location]

  /// The standard List next-page token.
  public var nextPageToken: String

  /// Initialize a new instance of `ListLocationsResponse`.
  public init(
    locations: [Location] = [],
    nextPageToken: String = String(),
  ) {
    self.locations = locations
    self.nextPageToken = nextPageToken
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.location.ListLocationsResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
