// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax

import GoogleCloudWkt

/// An abstract interface that provides location-related information for
/// a service. Service-specific metadata is provided through the
/// [Location.metadata][google.cloud.location.Location.metadata] field.
///
/// [google.cloud.location.Location.metadata]: <doc:Location/metadata>
///
/// @Snippet(path: "LocationsQuickstart")
public class Locations {
  let inner: GoogleCloudGax.HTTPClient

  /// Creates a new `Locations` instance.
  public init(
    endpoint: String? = nil,
    credentials: GoogleCloudAuth.Credentials? = nil,
    session: URLSession? = nil,
  ) throws {
    let endpoint = endpoint ?? "https://cloud.googleapis.com"
    self.inner = try HTTPClient(endpoint: endpoint, credentials: credentials, session: session)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Locations_ListLocations")
  public func listLocations(request: ListLocationsRequest) async throws
    -> ListLocationsResponse
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
      }
      return "/v1/\(pathVariable0)"
    }()
    var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    let encoder = GoogleCloudGax.QueryParameterEncoder()
    query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
    query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
    query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "GET"
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(ListLocationsResponse.self, from: data)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Locations_GetLocation")
  public func getLocation(request: GetLocationRequest) async throws
    -> Location
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
      }
      return "/v1/\(pathVariable0)"
    }()
    let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "GET"
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(Location.self, from: data)
  }
}
