// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudWkt
import Logging

/// An abstract interface that provides location-related information for
/// a service. Service-specific metadata is provided through the
/// [Location.metadata][google.cloud.location.Location.metadata] field.
///
/// [google.cloud.location.Location.metadata]: <doc:Location/metadata>
///
/// @Snippet(path: "LocationsQuickstart")
public protocol Locations {
  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Locations_ListLocations")
  func listLocations(request: ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse

  /// Lists information about the supported locations for this service.
  func listLocations(byItem: ListLocationsRequest) throws -> any AsyncSequence<Location, Error>

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Locations_GetLocation")
  func getLocation(request: GetLocationRequest) async throws -> GoogleCloudLocation.Location

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Locations_ListLocations")
  func listLocations(
    request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse

  /// Lists information about the supported locations for this service.
  func listLocations(
    byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Location, Error>

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Locations_GetLocation")
  func getLocation(
    request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location
}

extension Clients {
  /// The recommended implementation for ``Locations``.
  public class LocationsClient: Locations {
    let inner: any LocationsStub

    /// Creates a new `LocationsClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any LocationsStub = try LocationsTransport(options)
      inner = LocationsRetry(inner, options: options)
      if let logger = options.logger {
        inner = LocationsLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// See `Locations.listLocations`
    public func listLocations(
      request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    public func listLocations(
      byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Location, Error> {
      let listRpc = { (token: String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `Locations.getLocation`
    public func getLocation(
      request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self.inner.getLocation(request: request, options: options)
    }
  }
}

// Default implementations
extension Locations {
  public func listLocations(request: ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(byItem: ListLocationsRequest) throws -> any AsyncSequence<
    Location, Error
  > {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Location, Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GetLocationRequest) async throws -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
