// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A resource that represents Google Cloud Platform location.
public struct Location: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Resource name for the location, which may vary between implementations.
  /// For example: `"projects/example-project/locations/us-east1"`
  public var name: Swift.String = Swift.String()

  /// The canonical id for this location. For example: `"us-east1"`.
  public var locationId: Swift.String = Swift.String()

  /// The friendly name for this location, typically a nearby city name.
  /// For example, "Tokyo".
  public var displayName: Swift.String = Swift.String()

  /// Cross-service attributes for the location. For example
  ///
  ///     {"cloud.googleapis.com/region": "us-east1"}
  public var labels: [Swift.String: Swift.String] = [:]

  /// Service-specific metadata. For example the available capacity at the given
  /// location.
  public var metadata: GoogleCloudWkt.`Any`? = nil

  /// Initialize a new instance of `Location`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Location().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.location.Location"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
